version : '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-django
    ports:
      - "8002:8001"
    volumes:
      - .:/src
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    restart: always
    build: .
    container_name: web-django-todo
    volumes:
      - .:/usr/src/app
    expose:
      - "8001"
    command: gunicorn -c project/conf.py project.wsgi
    depends_on:
      - db

  db:
    image: bitnami/postgresql
    container_name: postgresql-todo
    volumes:
      - /Users/fahmi/Documents/docker_volume/postgresql-bitnamo-1/:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=root
    ports:
      - "5432:5432"

#    python3 /usr/src/app/project/src/manage.py runserver 0.0.0.0:8001
#    command: ["gunicorn", "-c", "project/conf.py", "project.wsgi"]
#python manage.py makemigrations && python manage.py migrate &&


#nginx:
#  build: ./nginx
#  volumes:
#    - .:/usr/src/app
#  links:
#    - django
#  ports:
#    - "80:80"
