version : '3'

services:
  web:
    build: .
    container_name: web-django-todo
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    command: python project/src/manage.py runserver 8000
    depends_on:
      - db

  db:
    image: bitnami/postgresql
    container_name: postgresql-todo
    volumes:
      - /Users/fahmi/Documents/docker_volume/postgresql-bitnamo-1/:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=root
    ports:
      - "5432:5432"
