FROM python:3

WORKDIR /usr/src/app

COPY . .

RUN pip install -r project/requirements.txt

EXPOSE 8000

#ENTRYPOINT ["/usr/src/app/"]

CMD ["python3", "project/src/manage.py", "runserver", "0.0.0.0:8000"]
